---
collections:
# Install community.kubernetes Ansible Collection
- name: kubernetes.core
  version: 2.0.0
  source: https://galaxy.ansible.com

# Install amazon.aws Ansible Collection
- name: amazon.aws
  version: 1.5.0
  source: https://galaxy.ansible.com
