---
- name: OCP Testing
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get list of all pods from namespace
      community.kubernetes.k8s_info:
        kind: Pod
        namespace: "{{ ns }}"
      register: pod_list

#    - debug:
#        msg: "{{ pod_list.resources[0].spec.containers[0].name }}"
#
    - debug:
        msg: "{{ pod_list.resources[0].status.containerStatuses[0].name }}"

    - debug:
        msg: "{{ pod_list.resources[0].status.containerStatuses[0].state }}"

    - debug:
        msg: "{{ pod_list.resources[0].status.containerStatuses[0].state }}"
      when: 'running' in pod_list.resources[0].status.containerStatuses[0].state
