---
- name: Download Windows Server ISO to VMware Datastore
  get_url:
    url: 'http://{{ new_build_vars.windows_unattended_install.webserver.ip_address }}/{{ new_build_vars.windows_unattended_install.webserver.windows_server_iso_download_directory }}/{{ new_build_vars.windows_unattended_install.iso_build.windows_server_iso_name }}'
    tmp_dest: "{{ new_build_vars.windows_unattended_install.vmware_cluster.datastore_path }}"
    dest: "{{ new_build_vars.windows_unattended_install.vmware_cluster.datastore_path }}"

- name: Download ISO with autounattend.xml to VMware Datastore
  get_url:
    url: 'http://{{ new_build_vars.windows_unattended_install.webserver.ip_address }}/{{ new_build_vars.windows_unattended_install.webserver.unattended_iso_download_directory }}/{{ new_build_vars.windows_unattended_install.iso_build.unattended_iso_name }}'
    tmp_dest: "{{ new_build_vars.windows_unattended_install.vmware_cluster.datastore_path }}"
    dest: "{{ new_build_vars.windows_unattended_install.vmware_cluster.datastore_path }}"

- name: Create Windows 2019 Base Virtual Machine
  community.vmware.vmware_guest:
    datacenter: "{{ new_build_vars.windows_unattended_install.vmware_cluster.data_center }}"
    cluster: "{{ new_build_vars.windows_unattended_install.vmware_cluster.cluster }}"
    folder: "{{ new_build_vars.windows_unattended_install.vmware_cluster.folder }}"
    validate_certs: no
    name: "{{ new_build_vars.windows_unattended_install.vmware_cluster.windows_base_vm.name }}"
    state: poweredon
    disk:
    - size_mb: "{{ new_build_vars.windows_unattended_install.vmware_cluster.windows_base_vm.disk_mb }}"
      type: thin
      datastore: "{{ new_build_vars.windows_unattended_install.vmware_cluster.datastore_name }}"
    hardware:
      memory_mb: "{{ new_build_vars.windows_unattended_install.vmware_cluster.windows_base_vm.memory_mb }}"
      num_cpus: "{{ new_build_vars.windows_unattended_install.vmware_cluster.windows_base_vm.cpu }}"
      scsi: "{{ new_build_vars.windows_unattended_install.vmware_cluster.windows_base_vm.scsi }}"
    guest_id: "{{ new_build_vars.windows_unattended_install.vmware_cluster.guest_id }}"
    cdrom:
    - controller_type: sata
      controller_number: 0
      unit_number: 0
      type: iso
      iso_path: "[{{ new_build_vars.windows_unattended_install.vmware_cluster.datastore_name }}] {{ new_build_vars.windows_unattended_install.iso_build.windows_server_iso_name }}"
    - controller_type: sata
      controller_number: 0
      unit_number: 1
      type: iso
      iso_path: "[{{ new_build_vars.windows_unattended_install.vmware_cluster.datastore_name }}] {{ new_build_vars.windows_unattended_install.iso_build.unattended_iso_name }}"
    networks:
    - name: "{{ new_build_vars.windows_unattended_install.vmware_cluster.network_name }}"
      start_connected: yes
  delegate_to: localhost
