---
- name: Return next 2 available IP addresses for network "{{ ipam_network }}", excluding gateway IPs
  set_fact:
    ipaddr: "{{ lookup('nios_next_ip', num=2, ipam_network, exclude=subnet_gateway.split(','),
                provider=nios_provider) }}"
  delegate_to: localhost

- name: Print next 2 available IPs
  debug:
    var: ipaddr
  delegate_to: localhost

- name: Save information of next 2 available IP for subsequent workflow
  set_stats:
    data:
      ipv4_address: "{{ ipaddr }}"
  delegate_to: localhost
