---
- name: Apply JBoss EAP Patch
  command: "{{ jboss_eap_home }}/bin/jboss-cli.sh {{ '--command=' ~ cmd | quote }}"
  vars:
    cmd: >-
      patch apply /tmp/{{ jboss_eap_patch_artifact_name }} --verbose --override-all
