---
- name: TFTP New System Image to Boot Flash Memory
  ios_command:
    commands: 'copy tftp://{{ tftp_server_ip }}/{{ new_system_image }} bootflash:'
    wait_for: result[0] contains OK

- name: Print list of all files and directories in bootflash memory 
  ios_command:
    commands: 'dir bootflash:'
