---
- name: TFTP New System Image to Boot Flash Memory
  vars:
    ansible_command_timeout: 10
  ios_command:
    commands:
      - command: 'copy tftp://{{ tftp_server_ip }}/{{ new_system_image }} bootflash:'
        prompt: 'Destination filename \[{{ new_system_image }}\]'
        answer: "\r"
    interval: 10
    retries: "{{ number_of_retries | int }}"
    wait_for: result[0] contains OK

- name: Print list of all files and directories in bootflash memory 
  ios_command:
    commands: 'dir bootflash:'
