---
#- name: TFTP New System Image to Boot Flash Memory
#  vars:
#    ansible_command_timeout: 600
#  ios_command:
#    commands:
#      - command: 'copy tftp://{{ tftp_server_ip }}/{{ new_system_image }} bootflash:'
#        prompt: 'Destination filename \[{{ new_system_image }}\]'
#        answer: "\r"
#    interval: 10
#    retries: "{{ number_of_retries | int }}"
#    wait_for: result[0] contains OK

- name: Print List of all Files and Directories in bootflash Memory 
  ios_command:
    commands: 'dir bootflash:'

- name: Verify Image File Integrity
  vars:
    ansible_command_timeout: 60
  ios_command:
    commands: 'verify bootflash:/{{ new_system_image }}'
  register: image_verification_results

- name: Set image_integrity_check to pass/fail
  set_fact:
    image_integrity_check: "{{ 'pass' if 'Digital signature successfully verified' in image_verification_results.stdout[0].split('\n')[-1] else 'fail' }}"

- debug:
    msg: "{{ image_integrity_check }}"
