---
- name: Update Fortinet Firewall Policy
  fortios_ipv4_policy:
    host: "{{ ansible_host }}"
    username: "{{ fortinet_username }}"
    password: "{{ fortinet_password }}"
    id: "{{ random_id | int }}"
    src_addr: "{{ fortigate_firewall[fw]['source'] }}"
    dst_addr: "{{ fortigate_firewall[fw]['destination'] }}"
    service: "{{ fortigate_firewall[fw]['services'][item] }}"
    state: "{{ firewall_rule_state }}"
    policy_action: "{{ policy_action }}"
  loop: "{{ range(0, fortigate_firewall[fw]['services']|length)|list }}"

- name: Update Fortinet Firewall Policy in Reverse Direction
  fortios_ipv4_policy:
    host: "{{ ansible_host }}"
    username: "{{ fortinet_username }}"
    password: "{{ fortinet_password }}"
    id: "{{ random_id | int }}"
    src_addr: "{{ fortigate_firewall[fw]['destination'] }}"
    dst_addr: "{{ fortigate_firewall[fw]['source'] }}"
    service: "{{ fortigate_firewall[fw]['services'][item] }}"
    state: "{{ firewall_rule_state }}"
    policy_action: "{{ policy_action }}"
  loop: "{{ range(0, fortigate_firewall[fw]['services']|length)|list }}"
