---
- name: Create ACL (Bi-directional)
  ios_config:
    lines:
#      - "permit ip {{ ip_mask.src_ip[item|int -1] }} {{ ip_mask.src_mask[item|int -1] }} {{ ip_mask.dest_ip[item|int -1] }} {{ ip_mask.dest_mask[item|int -1] }}"
#      - "permit ip {{ ip_mask.dest_ip[item|int -1] }} {{ ip_mask.dest_mask[item|int -1] }} {{ ip_mask.src_ip[item|int -1] }} {{ ip_mask.src_mask[item|int -1] }}"
       - "{% for i in range(number_of_ip_segments|int + 1) %}permit {{ ip_protocol[i] }} {{ ip_mask.src_ip[item|int -1] }} {{ ip_mask.src_mask[item|int -1] }} {{ ip_mask.dest_ip[item|int -1] }} {{ ip_mask.dest_mask[item|int -1] }},{% endfor %}"
    parents: "ip access-list extended {{ ip_access_list }}"
    multiline_delimiter: ','
  loop:
  - { src_ip: "{{ source_ip_segment.split(',') }}", src_mask: "{{ source_ip_segment_mask.split(',') }}", dest_ip: "{{ destination_ip_segment.split(',') }}", dest_mask: "{{ destination_ip_segment_mask.split(',') }}" }
  loop_control:
    loop_var: ip_mask
