---
- name: Backup current config and Create ACL
  ios_config:
    lines:
      - "permit ip {{ source_ip_segment }} {{ source_ip_segment_mask }} {{ destination_ip_segment }} {{ destination_ip_mask }}"
    parents: "ip access-list extended {{ ip_access_list }}"
    backup: yes
  loop:
  - "{{ source_ip_segment.split(',') }}"
  - "{{ source_ip_mask.split(',') }}"
  - "{{ destination_ip_segment.split(',') }}"
  - "{{ destination_ip_mask.split(',') }}"

- name: Save running to startup when modified
  ios_config:
    save_when: modified
