---
- name: Backup current config and Create ACL
  ios_config:
    lines:
      - "permit ip {{ source_ip_segment }} {{ source_ip_segment_mask }} {{ destination_ip_segment }}"
    parents: ip access-list extended acl_mgmt
    before: no ip access-list extended acl_mgmt
    match: exact
    backup: yes

- name: Apply Management ACL
  ios_config:
    lines:
      - "ip access-group acl_mgmt in"
    parents: interface GigabitEthernet1

- name: Save running to startup when modified
  ios_config:
    save_when: modified
