---
- name: Backup current running config
  ios_config:
    backup: yes

- include_tasks: add_acl.yml
  with_sequence: start=1 end={{ number_of_ip_segments }}

- name: Save running config to startup when modified
  ios_config:
    save_when: modified
