---
- name: Update Fortinet Firewall Rule
  hosts: "{{ fortinet_firewall_ip }}"
  gather_facts: True
  vars:
    number_of_ip_segments: "{{ source_ip_segment.split(',') | length }}"

  tasks:
  - name: Update ACL
    include_role:
      name: fortinet_update_firewall_rule
      vars_from: "password.yml"
