---
- name: OC Login to DC-1
  command: "/usr/bin/oc login --insecure-skip-tls-verify -u {{ oc_user }} -p {{ oc_password }} {{ dc1_oc_api_endpoint }}"

- name: Get Token for DC-1
  command: "/usr/bin/oc whoami -t"
  register: oc_token_dc1

- name: Copy Image from QA to DC-1
  shell: "skopeo copy docker{% raw %}:{% endraw %}//{{ dc1_integrated_registry }}/{{ oc_project }}-qa/nodejs-demo{% raw %}:{% endraw %}qa docker{% raw %}:{% endraw %}//{{ dc1_integrated_registry }}/{{ oc_project }}/nodejs-demo --src-creds {{ oc_user }}{% raw %}:{% endraw %}{{ oc_token_dc1.stdout }} --dest-creds {{ oc_user }}{% raw %}:{% endraw %}{{ oc_token_dc1.stdout }} --dest-tls-verify=false --src-tls-verify=false"

- name: OC Login to DC-2
  command: "/usr/bin/oc login --insecure-skip-tls-verify -u {{ oc_user }} -p {{ oc_password }} {{ dc2_oc_api_endpoint }}"

- name: Get Token for DC-2
  command: "/usr/bin/oc whoami -t"
  register: oc_token_dc2

- name: Copy Image from QA to DC-2
  shell: "skopeo copy docker{% raw %}:{% endraw %}//{{ dc1_integrated_registry }}/{{ oc_project }}-qa/nodejs-demo{% raw %}:{% endraw %}qa docker{% raw %}:{% endraw %}//{{ dc2_integrated_registry }}/{{ oc_project }}/nodejs-demo --src-creds {{ oc_user }}{% raw %}:{% endraw %}{{ oc_token_dc1.stdout }} --dest-creds {{ oc_user }}{% raw %}:{% endraw %}{{ oc_token_dc2.stdout }} --dest-tls-verify=false --src-tls-verify=false"
