---
- name: Install and start apache
  hosts: web_servers
  become: yes

  tasks:
    - name: Ensure httpd package is present
      yum:
        name: httpd
        state: latest
  
    - name: Generate index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/
  
    - name: Ensure httpd is started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
  
    - name: Ensure firewalld package is present
      yum:
        name: firewalld
        state: latest
  
    - name: Ensure firewalld is started
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
  
    - name: Allow http traffic
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
