---
- name: Create ServiceNow Change Record
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create an incident
      snow_record:
        username: admin
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        data:
          short_description: "This is a test incident opened by Ansible for {{ app_name }}"
          severity: 3
          priority: 2
