---
- name: Deploy EC2 Instance
  hosts: localhost
  gather_facts: false

  tasks:
    - name:
      amazon.aws.ec2_eni:
        private_ip_address: "{{ ec2_private_ip }}"
        subnet_id: "{{ vpc_subnet_id }}"
        state: present
      register: ec2_instance_eni

    - debug:
        msg: "{{ ec2_instance_eni }}"

#    - name: Deploy VM in AWS
#      amazon.aws.ec2:
#        key_name: "{{ aws_key }}"
#        instance_type: "{{ instance_type }}"
#        image: "{{ ami_image }}"
#        group: "{{ security_group_name }}"
#        region: "{{ aws_region }}"
#        wait: yes
#        wait_timeout: 600
#        count: "{{ instance_count }}"
#        vpc_subnet_id: "{{ vpc_subnet_id }}"
#        assign_public_ip: "{{ assign_public_ip }}"
