---
- name: Configure MySQL Agent Monitoring
  hosts: db_servers
  become: yes

  tasks:
#    # Uncomment and execute this task if you are not intending to use GitOps approach
#    # from Instanta to place the configuration file 
#    - name: Create configuration file for mysql plugin
#      ansible.builtin.template:
#        src: templates/instana_mysql_configuration.yaml.j2
#        dest: "{{ agent_install_directory }}/etc/instana/mysql_configuration.yaml"
#
    - name: Generate sql commands file
      ansible.builtin.template:
        src: templates/instana_mon_setup.sql.j2
        dest: /tmp/instana_mon_setup.sql

    - name: Grant required DB permissions
      ansible.builtin.shell: mysql < /tmp/instana_mon_setup.sql

    - name: Ensure deploy directory exists
      ansible.builtin.file:
        path: "{{ agent_install_directory }}/deploy"
        state: directory

    - name: Copy MySQL driver jar file
      ansible.builtin.copy:
        src: files/mysql-connector-java.jar
        dest: "{{ agent_install_directory }}/deploy/mysql-connector-java-{{ mysql_java_connector_version }}.jar"

    - name: Restart Instana Agent service
      ansible.builtin.service:
        name: instana-agent
        state: restarted

    - name: Remove sql commands files
      ansible.builtin.file:
        path: /tmp/instana_mon_setup.sql
        state: absent
