---
- name: Dump Current State of IOS Device
  vars:
    ansible_command_timeout: 60
  ios_command:
    commands:
      - show ip interface brief
      - show version
      - show vlan

- name: Ping Tests to Gateways
  vars:
    ansible_command_timeout: 60
  block:
    - name: Ping "{{ item }}"
      ios_command:
        commands: 'ping {{ item }}'
      register: ping_test_results

    - name: Set ping_test_check to pass/fail
      set_fact:
        ping_test_check: "{{ 'pass' if 'Success rate is 100 percent' in ping_test_results.stdout[0].split('\n')[-1] else 'fail' }}"

    - name: Fail Task if Ping Test Fails
      fail:
        msg: "Ping Test to {{ item }} Fails. Please check network connectivity!"
      when: ping_test_check == 'fail'
  loop: "{{ list_of_gateways }}"

- name: Print List of all Files and Directories in bootflash Memory 
  ios_command:
    commands: 'dir bootflash:'

- name: Set File Prompt to Quiet
  ios_config:
    lines: file prompt quiet

- name: Copy startup Configuration file to TFTP Server
  ios_command:
    commands: 'copy nvram:startup-config tftp://{{ tftp_server_ip }}/{{ startup_config_backup_file }}'

- name: Copy running Configuration file to TFTP Server
  ios_command:
    commands: 'copy nvram:running-config tftp://{{ tftp_server_ip }}/{{ running_config_backup_file }}'

- name: Disable Silent File Prompt
  ios_config:
    lines: no file prompt quiet

- name: Write Memory
  ios_command:
    commands: 'write memory'
