---
- name: Add Web Application VM to Tower Inventory
  tower_host:
    name: "{{ vm_hostname }}"
    description: "Add {{ vm_name }} to Tower Inventory"
    inventory: "VMWare_VM_Provisioning"
    state: present
    tower_verify_ssl: no
    variables: |+
      ---
      ansible_host: "{{ ipv4_address }}"

- name: Add host to webapp group
  command: tower-cli host associate --host "{{ vm_name }}" --group webapp
