---
- name: Check that required information has been provided
  assert:
    that:
      - java_home is defined
      - java_version is defined
      - jboss_home is defined
      - jdk_id is defined
    fail_msg: "java_home, java_version, jdk_id and jboss_home must defined."
    quiet: true

- set_fact:
    compliance_violations: 0
    compliance_issues: []

- name: Analyse Informational Headers
  include_tasks: tasks/jboss_cli.yml
  vars:
    query: '{{ informational_headers.query }}'

- name: Check that Informational Headers are Compliant
  include_tasks: informational_headers_compliance.yml

- name: Analyse Stack Trace
  include_tasks: tasks/jboss_cli.yml
  vars:
    query: '{{ stack_trace.query }}'

- name: Check that Stack Trace are Compliant
  include_tasks: stack_trace_compliance.yml

- name: Analyse TLS version
  include_tasks: tasks/jboss_cli.yml
  vars:
    query: '{{ tls_version.query }}'

- name: Check that TLS version is Compliant
  include_tasks: tls_compliance.yml

- name: Analyse welcome-content Handler
  include_tasks: tasks/jboss_cli.yml
  vars:
    query: '{{ welcome_web_app.query }}'

- name: Check that welcome-content handler is Compliant
  include_tasks: welcome_web_app_compliance.yml

- block:
    - debug:
        msg: "{{ item }}"
      loop: "{{ compliance_issues }}"

    - name: "Display list of CC violations"
      debug:
        msg: "Number of violations of Common Criteria recommendations: {{ compliance_violations }}."
      changed_when: override_changed_when_if_cc_violations | default(True)
  when:
    - compliance_violations is defined
