---
- name: Create json file from a template
  ansible.builtin.template:
    src: templates/create_host.json.j2
    dest: create_host.json

- name: Add Host to Inventory
  uri:
    url: "{{ controller_host }}/api/v2/inventories/{{ new_build_vars.windows_unattended_install.ansible_controller.inventory_id }}/hosts/"
    method: POST
    user: "{{ controller_username }}"
    password: "{{ controller_password }}"
    body: "{{ lookup('file','create_host.json') }}"
    force_basic_auth: yes
    body_format: json
    headers:
      Content-Type: application/json
    status_code: 201
    validate_certs: no
  no_log: true

- name: Add Host to Windows Server Group
  uri:
    url: "{{ controller_host }}/api/v2/groups/{{ new_build_vars.windows_unattended_install.ansible_controller.group_id }}/hosts/"
    method: POST
    user: "{{ controller_username }}"
    password: "{{ controller_password }}"
    body:
      name: "{{ new_build_vars.windows_unattended_install.vmware_cluster.windows_base_vm.name }}"
      inventory: "{{ new_build_vars.windows_unattended_install.ansible_controller.inventory_id }}"
    force_basic_auth: yes
    body_format: json
    headers:
      Content-Type: application/json
    status_code: 204
    validate_certs: no
  no_log: true
