---
- name: Remove Linux Virtual Machine
  vmware_guest:
    datacenter: "{{ vm_datacenter }}"
    validate_certs: no
    name: "{{ item }}"
    state: absent
    esxi_hostname: "{{ esxi_host }}"
    force: yes
  loop: "{{ vm_hostname }}"
  delegate_to: localhost
