---
- name: Update VMware Tools, if needed
  block:
    - name: Get VM UUID
      community.vmware.vmware_guest_info:
        datacenter: "{{ new_build_vars.windows_unattended_install.vmware_cluster.data_center }}"
        folder: "{{ new_build_vars.windows_unattended_install.vmware_cluster.folder }}"
        name: "{{ new_build_vars.windows_unattended_install.vmware_cluster.windows_base_vm.name }}"
        validate_certs: no
      register: vm_facts

    - name: Upgrade VMware Tools, if needed
      community.vmware.vmware_guest_tools_upgrade:
        datacenter: "{{ new_build_vars.windows_unattended_install.vmware_cluster.data_center }}"
        folder: "{{ new_build_vars.windows_unattended_install.vmware_cluster.folder }}"
        uuid: "{{ vm_facts.instance.hw_product_uuid }}"
        validate_certs: no
  delegate_to: localhost
