---
- name: Add Windows Base Server to Inventory
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Add server to inventory
      include_role:
        name: add_inventory
        vars_from: secrets.yml