---
- name: Convert Windows Base Server VM to VMware Template
  hosts: bastion_host
  gather_facts: false

  tasks:
    - name: Convert VM to Template
      include_role:
        name: convert_windows_base_server_to_vmware_template
        vars_from: secrets.yml
