---
- name: Windows Server Hardening
  hosts: "{{ new_build_vars.windows_unattended_install.vmware_cluster.windows_base_vm.name }}"
  gather_facts: false

  pre_tasks:
    - name: Check connectivity to Windows Base VM
      wait_for_connection:
        delay: 300
        timeout: 600

  roles:
    - windows_hardening 
