---
- name: "Search-only, return list of found updates (if any), log to {{ check_win_updates_log_path }}"
  win_updates:
    category_names: "{{ win_update_category }}"
    state: searched
    log_path: "{{ check_win_updates_log_path }}"
  register: list_of_updates

- name: List Remaining Updates
  debug:
    msg: "{{ item.value.title }}"
  loop: "{{ list_of_updates.updates | dict2items }}"

- name: Flag if Required Update is not installed. Skip if update has been installed.
  debug:
    msg: "KB{{ item.value.title }} is not installed!"
  loop: "{{ list_of_updates.updates | dict2items }}"
  vars:
    windows_update_kb: "{{ win_update_whitelist }}"
  when: item.value.kb == windows_update_kb
