---
- name: "Search-only, return list of found updates (if any), log to {{ check_win_updates_log_path }}"
  win_updates:
    category_names: "{{ win_update_category }}"
    state: searched
    log_path: "{{ check_win_updates_log_path }}"
  register: list_of_updates

- name: Create Reports Directory
  file:
    path: reports
    state: directory
    mode: 0755
  delegate_to: localhost

- name: Template Rendering
  template:
    src: win_updates_report.j2
    dest: "reports/{{ inventory_hostname }}_report"
  delegate_to: localhost

- name: Consolidate List of Required Windows Updates
  assemble:
    src: reports/
    dest: reports/list_of_required_windows_updates_for_all_vm.yml
  delegate_to: localhost
  run_once: yes

#- name: Flag if Required Update is not installed. Skip if required update has been installed.
#  debug:
#    msg: "KB{{ item.value.title }} is not installed!"
#  loop: "{{ list_of_updates.updates | dict2items }}"
#  vars:
#    required_win_update: "{{ win_update_whitelist }}"
#  when: item.value.kb == required_win_update

- name: Send Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ gmail_account }}"
    password: "{{ gmail_account_password }}"
    to: Anthony Lin <anthony.lin.test@gmail.com>
    subject: "Ansible Report"
    body: "The list of required Windows Update for the Windows VMs can be found in the attached file"
    attach:
     - reports/list_of_required_windows_updates_for_all_vm.yml
  delegate_to: localhost
  run_once: yes
