---
- name: Fetch Private Key from Bastion
  hosts: tag_AnsibleGroup_bastions
  become: yes

  tasks:
  - name: Fetch Private Key from Bastion
    fetch:
      src: "/root/.ssh/{{ hostvars[inventory_hostname]['ec2_tag_Project'] | regex_replace('three-tier-app-','') }}key.pem"
      dest: /tmp/
      flat: yes

- name: Inject Key into Ansible Tower
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
  - name: Move Private Key to temporary location under home directory
    shell: mkdir -p {{ ansible_env.HOME }}/tmp && mv /tmp/*.pem {{ ansible_env.HOME }}/tmp/ && chmod 400 {{ ansible_env.HOME }}/tmp/*.pem

  - name: List files in temporary directory
    shell: ls -1 {{ ansible_env.HOME }}/tmp
    register: private_key

  - debug:
      msg: "{{ ansible_env.HOME }}/tmp/{{ private_key.stdout }}"

#  - name: Inject Key into Ansible Tower
#    tower_credential:
#      name: Three_Tier_Prod_Key
#      organization: Default
#      state: present
#      tower_host: "{{ tower_node }}.{{ tower_guid }}.{{ tower_domain_path }}"
#      tower_username: "{{ tower_username }}"
#      tower_password: "{{ tower_password }}"
#      kind: ssh
#      username: "{{ three_tier_user }}"
#      ssh_key_data: "{{ ansible_env.HOME }}/tmp/{{ private_key.stdout }}"
