---
- name: Retrieve new build requirements
  ansible.builtin.include_vars:
    file: files/unattended_install.yml
    name: new_build_requirements

- name: Capture new build information and use it for subsequent workflow
  ansible.builtin.set_stats:
    data:
      new_build_vars: "{{ new_build_requirements }}"
