---
- name: Perform Password Hardening
  include_tasks: password_section.yml
  when: "'password_section' in new_build_vars.windows_unattended_install.hardening_requirements"

- name: Perform Account Lockout Hardening
  include_tasks: account_lockout_section.yml
  when: "'account_lockout_section' in new_build_vars.windows_unattended_install.hardening_requirements"

- name: Perform Auditing Hardening
  include_tasks: auditing_section.yml
  when: "'auditing_section' in new_build_vars.windows_unattended_install.hardening_requirements"

- name: Perform Registry Fixes
  include_tasks: registry_fixes_section.yml
  when: "'registry_fixes_section' in new_build_vars.windows_unattended_install.hardening_requirements"
