---
- name: Palo Alto Firewall
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    PYTHONHTTPSVERIFY: 0

  tasks:
  - name: Create Firewall Rule
    include_role:
      name: create_panos_rule
      vars_from: "password.yml"
