---
# This playbook deploys simple applications to JBoss server
- name: Deploy Simple Application to JBoss Server
  hosts: localhost
  gather_facts: False
  vars:
    war_file: app-v1.0.war

  roles:
    - java-app
