---
collections:
  - name: geerlingguy.php_roles
    version: 0.9.3
    source: https://galaxy.ansible.com
#collections:
# Install community.kubernetes Ansible Collection
#- name: community.kubernetes
#  version: 1.0.0
#  source: https://galaxy.ansible.com
