---
- name: Delete all files in temporary build directory, if exists
  ansible.builtin.file:
    path: "{{ new_build_vars.windows_unattended_install.iso_build.build_directory }}"
    state: absent

- name: Create temporary build directory for ISO generation
  ansible.builtin.file:
    path: "{{ new_build_vars.windows_unattended_install.iso_build.build_directory }}"
    state: directory
    mode: '0755'

- name: Download vmware-tools to temporary build directory
  get_url:
    url: 'http://{{ new_build_vars.windows_unattended_install.webserver.ip_address }}/{{ new_build_vars.windows_unattended_install.vmware_tools.esx_67u3_download_path }}'
    dest: "{{ new_build_vars.windows_unattended_install.iso_build.build_directory }}/vmware-tools.exe"

- name: Copy ConfigureRemotingForAnsible.ps1
  ansible.builtin.copy:
    src: files/ConfigureRemotingForAnsible.ps1
    dest: "{{ new_build_vars.windows_unattended_install.iso_build.build_directory }}/ConfigureRemotingForAnsible.ps1"

- name: Generate autounattend.xml
  ansible.builtin.template:
    src: templates/autounattend.xml.j2
    dest: "{{ new_build_vars.windows_unattended_install.iso_build.build_directory }}/autounattend.xml"

- name: Generate set_default_ip_dns.ps1
  ansible.builtin.template:
    src: templates/set_default_ip_dns.ps1.j2
    dest: "{{ new_build_vars.windows_unattended_install.iso_build.build_directory }}/set_default_ip_dns.ps1"

- name: Delete win_unattended.iso, if exists
  ansible.builtin.file:
    path: "{{ new_build_vars.windows_unattended_install.iso_build.unattended_iso_path }}/{{ new_build_vars.windows_unattended_install.iso_build.unattended_iso_name }}"
    state: absent

# Note that the bastion host is also a webserver that is used for hosting files.
# Hence the ISO is created and placed in the appropriate path on the bastion host
- name: Create ISO with autounattend.xml for installation
  command: "mkisofs -J -l -R -o {{ new_build_vars.windows_unattended_install.iso_build.unattended_iso_path }}/{{ new_build_vars.windows_unattended_install.iso_build.unattended_iso_name }} {{ new_build_vars.windows_unattended_install.iso_build.build_directory }}"

- name: Clean up all files in temporary build directory
  ansible.builtin.file:
    path: "{{ new_build_vars.windows_unattended_install.iso_build.build_directory }}"
    state: absent
