---
- name: Shut down Windows Base Server
  community.vmware.vmware_guest_powerstate:
    folder: "{{ new_build_vars.windows_unattended_install.vmware_cluster.folder }}"
    name: "{{ new_build_vars.windows_unattended_install.vmware_cluster.windows_base_vm.name }}"
    state: shutdown-guest
    state_change_timeout: 120
    validate_certs: no
  delegate_to: localhost

- name: Delete convert_vm_to_template.ps1, if exists
  ansible.builtin.file:
    path: /tmp/convert_vm_to_template.ps1
    state: absent

- name: Generate powershell script
  ansible.builtin.template:
    src: templates/convert_vm_to_template.ps1.j2
    dest: /tmp/convert_vm_to_template.ps1

- name: Convert Windows Base Server to VMware Template
  ansible.builtin.command: pwsh /tmp/convert_vm_to_template.ps1

- name: Remove convert_vm_to_template.ps1
  ansible.builtin.file:
    path: /tmp/convert_vm_to_template.ps1
    state: absent
