---
- name: Query Table
  shell:
    cmd: |
      sqlplus -s /nolog << EOF
      connect {{ db_user }}/{{ db_password }}
      set linesize 10000
      set tab off
      set wrap off
      {{ db_action }} {{ db_columns }} from {{ db_table }};
      quit
      EOF
  register: query_output
  when: db_action == "select"

- name: Describe Table
  shell:
    cmd: |
      sqlplus -s /nolog << EOF
      connect {{ db_user }}/{{ db_password }}
      set tab off
      {{ db_action }} {{ db_table }};
      quit
      EOF
  register: query_output
  when: db_action == "describe"

- name: Fails Playbook if Error Detected
  fail:
    msg: "Following Errors Detected - {{ query_output.stdout_lines }}"
  when: '"ERROR:" in query_output.stdout_lines'

- name: Print Table Query Output
  debug:
    msg: "{{ query_output.stdout_lines }}"
