---
- name: Check if Palo Alto Firewall is ready
  panos_check:
    ip_address: "{{ hostvars[firewall_node].ansible_host }}"
    password: "{{ paloalto_password }}"

- name: Create Address Object using API Key
  panos_object:
    ip_address: "{{ hostvars[firewall_node].ansible_host }}"
    api_key: "{{ paloalto_key }}"
    addressobject: "{{ address_object_name }}"
    operation: '{{ object_action }}'
    address: "{{ object_address }}"
    address_type: 'ip-netmask'
    tag_name: "{{ object_tag }}"
    description: "{{ object_description }}"
