---
- name: Backup current running config
  ios_config:
    backup: yes

- name: Include vars from acl_config_update.yml
  include_vars:
    file: /tmp/acl_config_update.yml
  delegate_to: localhost

- name: Create ACL (bi-directional)
  ios_config:
    lines: "{{ cisco_routers_acl[inventory_hostname]['acl_rules'][item] }}"
    parents: "ip access-list extended {{ cisco_routers_acl[inventory_hostname]['ip_access_group'] }}"
  loop: "{{ range(0, cisco_routers_acl[inventory_hostname]['acl_rules']|length)|list }}"

- name: Apply ACL to interface
  ios_config:
    lines:
      - "ip access-group {{ cisco_routers_acl[inventory_hostname]['ip_access_group'] }} in"
    parents: "interface {{ cisco_routers_acl[inventory_hostname]['ip_interface'] }}"

- name: Save running config to startup when modified
  ios_config:
    save_when: modified
