---
- name: Rescan Current Status of Storage
  win_shell: Update-HostStorageCache

- name: Expand Windows Hard Disk
  win_shell: |
    $size = Get-PartitionSupportedSize -DriveLetter E
    Resize-Partition -DriveLetter E -Size $size.SizeMax
