---
- name: Compare the running-config against Golden config
  ios_config:
    diff_against: running
    intended_config: "{{ lookup('file', 'files/golden.cfg') }}"
  register: config_diff

- name: Print Config Difference, if any
  debug:
    msg: "{{ config_diff }}"
