---
- set_fact:
    running: "interface TenGigabitEthernet0/1/0\n description test"

- set_fact:
    intended: "interface GigabitEthernet0/1/0\n description test"

- ios_config:
    running_config: '{{ running }}'
    intended_config: '{{ intended }}'
    diff_against: intended

#- name: Get running config
#  ios_command:
#    commands: show running-config
#  register: current_running_config
#
#- name: Set fact for running config
#  set_fact:
#    running: "{{ current_running_config.stdout_lines[0] }}"
#
#- name: check the running-config against master config
#  ios_config:
#    running_config: "{{ running }}"
#    intended_config: "{{ lookup('file', 'golden.cfg') }}"
#    diff_against: intended
#  register: config_drift
#
#- name: Print Config Drift
#  debug:
#    msg: "{{ config_drift }}"

#- name: Get running config
#  ios_command:
#    commands: show running-config
#  register: running_config
#
#- name: Copy running config to running.cfg
#  copy:
#    content: "{{ running_config.stdout_lines }}"
#    dest: cisco_demo/roles/cisco_config_drift_check/files/running.cfg
#  delegate_to: localhost
#
#- name: Get Config Drift, if any
#  shell: 'diff cisco_demo/roles/cisco_config_drift_check/files/running.cfg cisco_demo/roles/cisco_config_drift_check/files/golden.cfg'
#  register: diff_config
#  delegate_to: localhost
#
#- name: Print Config Drift, if any
#  debug:
#    msg: "{{ diff_config }}"
