---
- name: Get running config
  ios_command:
    commands: show running-config
  register: current_running_config

- gen_diff:
    source: "{{ lookup('file', 'golden.cfg') }}"
    target: "{{ current_running_config.stdout[0] }}"
    source_type: string
    target_type: string
  register: config_drift

- name: Print Config Drift, if any
  debug:
    msg: "{{ config_drift.diff.delta }}"

#- name: check the running-config against master config
#  ios_config:
#    running_config: "{{ running }}"
#    intended_config: "{{ lookup('file', 'golden.cfg') }}"
#    diff_against: intended
#  register: config_drift
#
#- name: Print Config Drift
#  debug:
#    msg: "{{ config_drift }}"

#- name: Get running config
#  ios_command:
#    commands: show running-config
#  register: running_config
#
#- name: Copy running config to running.cfg
#  copy:
#    content: "{{ running_config.stdout_lines }}"
#    dest: cisco_demo/roles/cisco_config_drift_check/files/running.cfg
#  delegate_to: localhost
#
#- name: Get Config Drift, if any
#  shell: 'diff cisco_demo/roles/cisco_config_drift_check/files/running.cfg cisco_demo/roles/cisco_config_drift_check/files/golden.cfg'
#  register: diff_config
#  delegate_to: localhost
#
#- name: Print Config Drift, if any
#  debug:
#    msg: "{{ diff_config }}"
