---
- name: Get running config
  ios_command:
    commands: show running-config
  register: running_config

- name: Copy running config to running.cfg
  copy:
    content: "{{ running_config.stdout_lines }}"
    dest: running.cfg

- name: Get Config Drift, if any
  shell: 'diff running.cfg files/golden.cfg'
  register: diff_config

- name: Print Config Drift, if any
  debug:
    msg: "{{ diff_config }}"
