---
# For some reasons, the config drift functionalities for ios_config module
# did not work properly for my environment in ansible 2.7.1 (it always states
# that there is no configuration changes even when there is). The ideal approach
# should really be ito simply make use of the ios_config module, i.e.
#
#- name: check the running-config against master config
#  ios_config:
#    diff_against: intended
#    intended_config: "{{ lookup('file', 'golden.cfg') }}"
#  register: config_drift
#
# I had to make use of the diff module from https://github.com/cytopia/ansible-modules
# to get similar results
#
#
- name: Get running config
  ios_command:
    commands: show running-config
  register: current_running_config

- name: Check for Configuration Drift
  gen_diff:
    source: "{{ current_running_config.stdout[0] }}"
    target: "{{ lookup('file', 'golden.cfg') }}"
    source_type: string
    target_type: string
  register: config_drift

- name: Clean Up Reports Directory if it exists
  file:
    path: reports
    state: absent
  delegate_to: localhost
  run_once: yes

- name: Create Reports Directory
  file:
    path: reports
    state: directory
    mode: 0755
  delegate_to: localhost
  run_once: yes

- name: Render Template
  template:
    src: templates/config_drift_template.j2
    dest: reports/config_drift
  delegate_to: localhost

#- name: Remove Empty Lines in Report
#  lineinfile:
#    path: reports/config_drift
#    state: absent
#    regexp: '^\ *'
#  delegate_to: localhost
#  run_once: yes
