---
- name: Check if Palo Alto Firewall is ready
  panos_check:
    ip_address: "{{ firewall_node }}"
    password: "{{ paloalto_password }}"

- name: Export Palo Alto Configuration Prior to Creation of New Rule
  uri:
    url: "https://{{ firewall_node }}/api/?type=export&category=configuration&key={{ paloalto_key }}"
    validate_certs: no
    return_content: yes
  register: original_config

- name: Create Security Rule
  panos_security_rule:
    ip_address: "{{ firewall_node }}"
    username: "{{ paloalto_username }}"
    password: "{{ paloalto_password }}"
    operation: "{{ firewall_operation }}"
    rule_name: "{{ firewall_rule_name }}"
    source_ip: "{{ srcipaddress }}"
    source_user: 'any'
    destination_ip: "{{ dstipaddress }}"
    category: 'any'
    application: "{{ application }}"
    service: "{{ service }}"
    hip_profiles: 'any'
    action: "{{ firewall_action }}"
    devicegroup: "{{ device_group }}"

- name: Export Palo Alto Configuration After Creation of New Rule
  uri:
    url: "https://{{ firewall_node }}/api/?type=export&category=configuration&key={{ paloalto_key }}"
    validate_certs: no
    return_content: yes
  register: new_config

# Make use of https://github.com/cytopia/ansible-modules
- name: Show changes in configurations
  gen_diff:
    source: "{{ original_config }}"
    target: "{{ new_config }}"
    source_type: string
    target_type: string
  register: config_diff

- name: Print Differences, if any
  debug:
    msg: "{{ config_diff.diff.unified_diff }}"
  when: config_diff.changed
