---
- name: Backup Config
  ios_config:
    backup: yes
  register: config_output

- name: Rename Backup Config File
  copy:
    src: "{{config_output.backup_path}}"
    dest: "./backup/{{inventory_hostname}}.config"

- name: Remove Non Config Lines
  lineinfile:
    path: "./backup/{{ inventory_hostname }}.cfg"
    line: "Building configuration..."
    state: absent

- name: Remove Non Config Lines using Regular Expression
  lineinfile:
    path: "./backup/{{ inventory_hostname }}.cfg"
    regexp: 'Current configuration.*'
    state: absent

#- name: Archive Config
#  ios_command:
#    commands: archive config
#
#- name: Print list of config archives
#  ios_command:
#    commands: show archive
